In [8]:
import pandas as pd
import numpy as np
#import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
import matplotlib.pyplot as plt

### Step-1

In [9]:
dataset = pd.read_csv('./letter-recognition.csv')
dataset.head(5)

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [10]:
train_set = pd.DataFrame(data=None, columns = dataset.columns)
test_set = pd.DataFrame(data=None, columns = dataset.columns)
#train_set

### Step-2

In [11]:
def train_test_splitting(full_dataframe:pd.DataFrame, tgt_class:str):
    global train_set
    global test_set
    filtered_dataframe = full_dataframe[full_dataframe.letter==tgt_class]
    train, test = train_test_split(filtered_dataframe, test_size = 0.3)
    train_set = pd.concat([train_set,train], axis=0)
    test_set = pd.concat([test_set,test], axis=0)

In [12]:
dataset.letter.unique()

array(['T', 'I', 'D', 'N', 'G', 'S', 'B', 'A', 'J', 'M', 'X', 'O', 'R',
       'F', 'C', 'H', 'W', 'L', 'P', 'E', 'V', 'Y', 'Q', 'U', 'K', 'Z'],
      dtype=object)

### Step-3

In [13]:
for tgt_class in dataset.letter.unique():
    #print("target class is:",tgt_class)
    train_test_splitting(dataset, tgt_class)

In [14]:
train_set.letter.unique()

array(['T', 'I', 'D', 'N', 'G', 'S', 'B', 'A', 'J', 'M', 'X', 'O', 'R',
       'F', 'C', 'H', 'W', 'L', 'P', 'E', 'V', 'Y', 'Q', 'U', 'K', 'Z'],
      dtype=object)

In [15]:
test_set.letter.unique()

array(['T', 'I', 'D', 'N', 'G', 'S', 'B', 'A', 'J', 'M', 'X', 'O', 'R',
       'F', 'C', 'H', 'W', 'L', 'P', 'E', 'V', 'Y', 'Q', 'U', 'K', 'Z'],
      dtype=object)

In [16]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

### Step-4

In [17]:
X_train = train_set.drop(['letter'], axis=1)
y_train = train_set['letter']
X_test = test_set.drop(['letter'], axis=1)
y_test = test_set['letter']

In [18]:
type(X_train), type(X_test), type(y_train), type(y_test)

(pandas.core.frame.DataFrame,
 pandas.core.frame.DataFrame,
 pandas.core.series.Series,
 pandas.core.series.Series)

In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import svm
from sklearn.svm import SVC

In [30]:
print(dataset.min())
print(dataset.max())

letter    A
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: object
letter     Z
xbox      15
ybox      15
width     15
height    15
onpix     15
xbar      15
ybar      15
x2bar     15
y2bar     15
xybar     15
x2ybar    15
xy2bar    15
xedge     15
xedgey    15
yedge     15
yedgex    15
dtype: object

### As we can see that the range of the all independent variables is between 0 and 15 so standardization is not required

In [31]:
unique_letters = dataset['letter'].sort_values().unique()
#print(unique_letters)
accuracy_df = pd.DataFrame(unique_letters, columns = ['Class_label'])
accuracy_df['Linear_C1'] = np.NaN
accuracy_df['Linear_C5'] = np.NaN
accuracy_df['Linear_C10'] = np.NaN
accuracy_df['Polynomial_d2_C5'] = np.NaN
accuracy_df['Polynomial_d3_C5'] = np.NaN
accuracy_df['RBF_C5'] = np.NaN
accuracy_df

,Class_label,Linear_C1,Linear_C5,Linear_C10,Polynomial_d2_C5,Polynomial_d3_C5,RBF_C5
0,A,NaN,NaN,NaN,NaN,NaN,NaN
1,B,NaN,NaN,NaN,NaN,NaN,NaN
2,C,NaN,NaN,NaN,NaN,NaN,NaN
3,D,NaN,NaN,NaN,NaN,NaN,NaN
4,E,NaN,NaN,NaN,NaN,NaN,NaN
5,F,NaN,NaN,NaN,NaN,NaN,NaN
6,G,NaN,NaN,NaN,NaN,NaN,NaN
7,H,NaN,NaN,NaN,NaN,NaN,NaN
8,I,NaN,NaN,NaN,NaN,NaN,NaN
9,J,NaN,NaN,NaN,NaN,NaN,NaN
10,K,NaN,NaN,NaN,NaN,NaN,NaN
11,L,NaN,NaN,NaN,NaN,NaN,NaN
12,M,NaN,NaN,NaN,NaN,NaN,NaN
13,N,NaN,NaN,NaN,NaN,NaN,NaN
14,O,NaN,NaN,NaN,NaN,NaN,NaN
15,P,NaN,NaN,NaN,NaN,NaN,NaN
16,Q,NaN,NaN,NaN,NaN,NaN,NaN
17,R,NaN,NaN,NaN,NaN,NaN,NaN
18,S,NaN,NaN,NaN,NaN,NaN,NaN
19,T,NaN,NaN,NaN,NaN,NaN,NaN
20,U,NaN,NaN,NaN,NaN,NaN,NaN
21,V,NaN,NaN,NaN,NaN,NaN,NaN
22,W,NaN,NaN,NaN,NaN,NaN,NaN
23,X,NaN,NaN,NaN,NaN,NaN,NaN
24,Y,NaN,NaN,NaN,NaN,NaN,NaN
25,Z,NaN,NaN,NaN,NaN,NaN,NaN

### 1-vs-rest SVM classifier for each class

In [33]:
for i in range(0,len(accuracy_df['Class_label'])):
    class_label_iter = accuracy_df.iloc[i,0]

    svm_mod1 = svm.SVC(kernel='linear',C=1.0)
    svm_mod2 = svm.SVC(kernel='linear',C=5.0)
    svm_mod3 = svm.SVC(kernel='linear',C=10.0)
    svm_mod4 = svm.SVC(kernel='poly',C=5.0,degree=2)
    svm_mod5 = svm.SVC(kernel='poly',C=5.0,degree=3)
    svm_mod6 = svm.SVC(kernel='rbf',C=5.0)
    
    ####################################################
    svm_mod1.fit(X_train,y_train)
    y_pred1 = svm_mod1.predict(X_test)
    accuracy_mod1 = metrics.accuracy_score(y_test, y_pred1)
    print("Accuracy calculated for Class_label "+ class_label_iter + ": Model 1") 

    ####################################################
    svm_mod2.fit(X_train,y_train)
    y_pred2 = svm_mod2.predict(X_test)
    accuracy_mod2 = metrics.accuracy_score(y_test, y_pred2)
    print("Accuracy calculated for Class_label "+ class_label_iter + ": Model 2") 

    ####################################################
    svm_mod3.fit(X_train,y_train)
    y_pred3 = svm_mod3.predict(X_test)
    accuracy_mod3 = metrics.accuracy_score(y_test, y_pred3)
    print("Accuracy calculated for Class_label "+ class_label_iter + ": Model 3") 

    ####################################################
    svm_mod4.fit(X_train,y_train)
    y_pred4 = svm_mod4.predict(X_test)
    accuracy_mod4 = metrics.accuracy_score(y_test, y_pred4)
    print("Accuracy calculated for Class_label "+ class_label_iter + ": Model 4") 

    ####################################################
    svm_mod5.fit(X_train,y_train)
    y_pred5 = svm_mod5.predict(X_test)
    accuracy_mod5 = metrics.accuracy_score(y_test, y_pred5)
    print("Accuracy calculated for Class_label "+ class_label_iter + ": Model 5") 

    ####################################################
    svm_mod6.fit(X_train,y_train)
    y_pred6 = svm_mod6.predict(X_test)
    accuracy_mod6 = metrics.accuracy_score(y_test, y_pred6)
    print("Accuracy calculated for Class_label "+ class_label_iter + ": Model 6") 
    
    ####################################################
    accuracy_df.iloc[i,1] = accuracy_mod1
    accuracy_df.iloc[i,2] = accuracy_mod2
    accuracy_df.iloc[i,3] = accuracy_mod3
    accuracy_df.iloc[i,4] = accuracy_mod4
    accuracy_df.iloc[i,5] = accuracy_mod5
    accuracy_df.iloc[i,6] = accuracy_mod6

Accuracy calculated for Class_label A: Model 1
Accuracy calculated for Class_label A: Model 2
Accuracy calculated for Class_label A: Model 3
Accuracy calculated for Class_label A: Model 4
Accuracy calculated for Class_label A: Model 5
Accuracy calculated for Class_label A: Model 6
Accuracy calculated for Class_label B: Model 1
Accuracy calculated for Class_label B: Model 2
Accuracy calculated for Class_label B: Model 3
Accuracy calculated for Class_label B: Model 4
Accuracy calculated for Class_label B: Model 5
Accuracy calculated for Class_label B: Model 6
Accuracy calculated for Class_label C: Model 1
Accuracy calculated for Class_label C: Model 2
Accuracy calculated for Class_label C: Model 3
Accuracy calculated for Class_label C: Model 4
Accuracy calculated for Class_label C: Model 5
Accuracy calculated for Class_label C: Model 6
Accuracy calculated for Class_label D: Model 1
Accuracy calculated for Class_label D: Model 2
Accuracy calculated for Class_label D: Model 3
Accuracy calculated for Class_label D: Model 4
Accuracy calculated for Class_label D: Model 5
Accuracy calculated for Class_label D: Model 6
Accuracy calculated for Class_label E: Model 1
Accuracy calculated for Class_label E: Model 2
Accuracy calculated for Class_label E: Model 3
Accuracy calculated for Class_label E: Model 4
Accuracy calculated for Class_label E: Model 5
Accuracy calculated for Class_label E: Model 6
Accuracy calculated for Class_label F: Model 1
Accuracy calculated for Class_label F: Model 2
Accuracy calculated for Class_label F: Model 3
Accuracy calculated for Class_label F: Model 4
Accuracy calculated for Class_label F: Model 5
Accuracy calculated for Class_label F: Model 6
Accuracy calculated for Class_label G: Model 1
Accuracy calculated for Class_label G: Model 2
Accuracy calculated for Class_label G: Model 3
Accuracy calculated for Class_label G: Model 4
Accuracy calculated for Class_label G: Model 5
Accuracy calculated for Class_label G: Model 6
Accuracy calculated for Class_label H: Model 1
Accuracy calculated for Class_label H: Model 2
Accuracy calculated for Class_label H: Model 3
Accuracy calculated for Class_label H: Model 4
Accuracy calculated for Class_label H: Model 5
Accuracy calculated for Class_label H: Model 6
Accuracy calculated for Class_label I: Model 1
Accuracy calculated for Class_label I: Model 2
Accuracy calculated for Class_label I: Model 3
Accuracy calculated for Class_label I: Model 4
Accuracy calculated for Class_label I: Model 5
Accuracy calculated for Class_label I: Model 6
Accuracy calculated for Class_label J: Model 1
Accuracy calculated for Class_label J: Model 2
Accuracy calculated for Class_label J: Model 3
Accuracy calculated for Class_label J: Model 4
Accuracy calculated for Class_label J: Model 5
Accuracy calculated for Class_label J: Model 6
Accuracy calculated for Class_label K: Model 1
Accuracy calculated for Class_label K: Model 2
Accuracy calculated for Class_label K: Model 3
Accuracy calculated for Class_label K: Model 4
Accuracy calculated for Class_label K: Model 5
Accuracy calculated for Class_label K: Model 6
Accuracy calculated for Class_label L: Model 1
Accuracy calculated for Class_label L: Model 2
Accuracy calculated for Class_label L: Model 3
Accuracy calculated for Class_label L: Model 4
Accuracy calculated for Class_label L: Model 5
Accuracy calculated for Class_label L: Model 6
Accuracy calculated for Class_label M: Model 1
Accuracy calculated for Class_label M: Model 2
Accuracy calculated for Class_label M: Model 3
Accuracy calculated for Class_label M: Model 4
Accuracy calculated for Class_label M: Model 5
Accuracy calculated for Class_label M: Model 6
Accuracy calculated for Class_label N: Model 1
Accuracy calculated for Class_label N: Model 2
Accuracy calculated for Class_label N: Model 3
Accuracy calculated for Class_label N: Model 4
Accuracy calculated for Class_label N: Model 5
Accuracy calculated for Class_label N: Model 6
Accuracy calculated for Class_label O: Model 1
Accuracy calculated for Class_label O: Model 2
Accuracy calculated for Class_label O: Model 3
Accuracy calculated for Class_label O: Model 4
Accuracy calculated for Class_label O: Model 5
Accuracy calculated for Class_label O: Model 6
Accuracy calculated for Class_label P: Model 1
Accuracy calculated for Class_label P: Model 2
Accuracy calculated for Class_label P: Model 3
Accuracy calculated for Class_label P: Model 4
Accuracy calculated for Class_label P: Model 5
Accuracy calculated for Class_label P: Model 6
Accuracy calculated for Class_label Q: Model 1
Accuracy calculated for Class_label Q: Model 2
Accuracy calculated for Class_label Q: Model 3
Accuracy calculated for Class_label Q: Model 4
Accuracy calculated for Class_label Q: Model 5
Accuracy calculated for Class_label Q: Model 6
Accuracy calculated for Class_label R: Model 1
Accuracy calculated for Class_label R: Model 2
Accuracy calculated for Class_label R: Model 3
Accuracy calculated for Class_label R: Model 4
Accuracy calculated for Class_label R: Model 5
Accuracy calculated for Class_label R: Model 6
Accuracy calculated for Class_label S: Model 1
Accuracy calculated for Class_label S: Model 2
Accuracy calculated for Class_label S: Model 3
Accuracy calculated for Class_label S: Model 4
Accuracy calculated for Class_label S: Model 5
Accuracy calculated for Class_label S: Model 6
Accuracy calculated for Class_label T: Model 1
Accuracy calculated for Class_label T: Model 2
Accuracy calculated for Class_label T: Model 3
Accuracy calculated for Class_label T: Model 4
Accuracy calculated for Class_label T: Model 5
Accuracy calculated for Class_label T: Model 6
Accuracy calculated for Class_label U: Model 1
Accuracy calculated for Class_label U: Model 2
Accuracy calculated for Class_label U: Model 3
Accuracy calculated for Class_label U: Model 4
Accuracy calculated for Class_label U: Model 5
Accuracy calculated for Class_label U: Model 6
Accuracy calculated for Class_label V: Model 1
Accuracy calculated for Class_label V: Model 2
Accuracy calculated for Class_label V: Model 3
Accuracy calculated for Class_label V: Model 4
Accuracy calculated for Class_label V: Model 5
Accuracy calculated for Class_label V: Model 6
Accuracy calculated for Class_label W: Model 1
Accuracy calculated for Class_label W: Model 2
Accuracy calculated for Class_label W: Model 3
Accuracy calculated for Class_label W: Model 4
Accuracy calculated for Class_label W: Model 5
Accuracy calculated for Class_label W: Model 6
Accuracy calculated for Class_label X: Model 1
Accuracy calculated for Class_label X: Model 2
Accuracy calculated for Class_label X: Model 3
Accuracy calculated for Class_label X: Model 4
Accuracy calculated for Class_label X: Model 5
Accuracy calculated for Class_label X: Model 6
Accuracy calculated for Class_label Y: Model 1
Accuracy calculated for Class_label Y: Model 2
Accuracy calculated for Class_label Y: Model 3
Accuracy calculated for Class_label Y: Model 4
Accuracy calculated for Class_label Y: Model 5
Accuracy calculated for Class_label Y: Model 6
Accuracy calculated for Class_label Z: Model 1
Accuracy calculated for Class_label Z: Model 2
Accuracy calculated for Class_label Z: Model 3
Accuracy calculated for Class_label Z: Model 4
Accuracy calculated for Class_label Z: Model 5
Accuracy calculated for Class_label Z: Model 6

In [34]:
accuracy_df.to_csv("./q3_output.csv")

### Conclusion:

### what’s going on as C increases for Linear models: From the accuracy_df values (q3_output.csv), we can say that accuracy remains almost same even with change in C values

### what’s going on as Kernel goes from Linear, Polynomial, and RBF for C = 5: From the accuracy_df values (q3_output.csv), we can say that accuracy increases when Kernel goes from linear (C=5), Polynomial (C=5, d=2) and RBF (C=5) whereas accuracy of Polynomial (C=5, D=3) is almost same as RBF